--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpa-php-apache
  region: us-west-2
  
managedNodeGroups:
  - name: ng2-managed
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  